config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  resources :apps
  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: 'home#index'

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind' => 'users#auth_unbind', as: 'unbind_account'
  post 'account/update_private_token' => 'users#update_private_token', as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id' => 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed' => 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last' => 'topics#recent', as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
      post :ban
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search' => 'search#index', as: 'search'

  namespace :cpanel do
    root to: 'home#index'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
  end

  get 'api' => 'home#api', as: 'api'
  get 'twitter' => 'home#twitter', as: 'twitter'
  get 'markdown' => 'home#markdown', as: 'markdown'

  require 'dispatch'
  mount Api::Dispatch => '/api'

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get 'users/city/:id' => 'users#city', as: 'location_users'
  get 'users' => 'users#index', as: 'users'
  resources :users, path: '' do
    member do
      get :topics
      get :favorites
      get :notes
      get :blocked
      post :block
      post :unblock
      post :follow
      post :unfollow
      get :followers
      get :following
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/models/note.rb
# 记事本
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  include Redis::Objects

  field :title
  field :body
  field :word_count, type: Integer
  field :changes_count, type: Integer, default: 0
  field :publish, type: Mongoid::Boolean, default: false
  belongs_to :user

  counter :hits, default: 0

  index user_id: 1
  index updated_at: -1

  scope :recent_updated, -> { desc(:updated_at) }
  scope :published, -> { where(publish: true) }

  before_save :auto_set_value
  def auto_set_value
    unless body.blank?
      self.title = body.split("\n").first[0..50]
      self.word_count = body.length
    end
  end

  before_update :update_changes_count
  def update_changes_count
    self.changes_count = 0 if changes_count.blank?
    inc(changes_count: 1)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user, except: [:show]
  load_and_authorize_resource

  def index
    @notes = current_user.notes.recent_updated.paginate(page: params[:page], per_page: 20)
    set_seo_meta t('menu.notes')
  end

  def show
    @note = Note.find(params[:id])
    @note.hits.incr(1)
    set_seo_meta("查看 &raquo; #{t('menu.notes')}")
  end

  def new
    @note = current_user.notes.build
    set_seo_meta("新建 &raquo; #{t('menu.notes')}")
  end

  def edit
    @note = current_user.notes.find(params[:id])
    set_seo_meta("修改 &raquo; #{t('menu.notes')}")
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.publish = note_params[:publish] == '1'
    if @note.save
      redirect_to(@note, notice: t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update_attributes(note_params)
      redirect_to(@note, notice: t('common.update_success'))
    else
      render action: 'edit'
    end
  end

  def preview
    render text: MarkdownConverter.convert(params[:body])
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    redirect_to(notes_url)
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :publish)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def render_node_topics_count(node)
    node.topics_count
  end

  def render_node_name(name, id)
    link_to(name, node_topics_path(id), class: 'node')
  end

  def note_title_tag(note, opts = {})
    opts[:limit] ||= 50
    return '' if note.blank?
    return '' if note.title.blank?
    truncate(note.title.delete('#'), length: opts[:limit])
  end
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note, html: { class: "" }) do |f| %>
    <%= render "shared/error_messages", target: @note %>
    <div class="form-group">
      <div class="editor-toolbar">
          <ul class="nav nav-pills" style="clear:none;">
            <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
            <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
          </ul>
      </div>
    </div>

    <div class="form-group">
      <%= f.text_area :body, class: "form-control", rows: 20 %>
      <p class="help-block">
      <%= t("notes.please_use") %> <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> <%= t("notes.document_format_to_write") %>
      </p>
    </div>

    <div class="form-group">
      <label class="control-label" for="note_publish"><%= f.check_box :publish %> <%= t("common.public")%></label>
    </div>

    <div class="form-group">
      <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving") %>
      <a href="<%= notes_path %>" class="btn btn-default"><%= t("common.cancel") %></a>
    </div>
<% end %>

app/views/notes/_sidebar.html.erb
<div class="sidebar col-md-3">
  <div class="panel panel-default">
    <div class="panel-heading">记事本是什么？</div>
    <div class="panel-body">
      <p>这是一个基于云存储的网络记事本，你可以放心的把你的一些文本资料存放在此处。</p>
      <p><a href="<%= new_note_path %>" class="btn btn-success">新建记事</a></p>
    </div>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="panel panel-default">
    <div class="panel-heading">提示</div>
    <ul class="list-group">
      <li class="list-group-item">记事的第一行将自动成为标题</li>
      <li class="list-group-item">超级链接会自动转换为可点击的状态</li>
      <li class="list-group-item">目前只支持纯文本格式</li>
      <li class="list-group-item">记事本的内容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><%= t("notes.edit_note")%></div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

app/views/notes/index.html.erb
<div class="row">
<div class="col-md-9">
  <div id="notes" class="panel panel-default">
    <div class="panel-heading">
      我的记事本
      <span class="total pull-right">
      已有 <%= current_user.notes.count %> 条记事
      </span>
    </div>

    <div class="panel-body">
    <% if @notes.blank? %>
      <div style="text-align:center; padding:60px 0;">你还没有创建过一个文件。</div>
    <% else %>

      <div>
      <% @notes.each do |note| %>
        <div class="media">
          <div class="media-body">
            <div class="media-heading">
              <i class="fa fa-file-text-o"></i> <a class="title" href="<%= note_path(note.id) %>"><%= truncate(note.title.gsub('#',''), length: 50) %></a> <%= raw '<span class="label warning"><i class="fa fa-share-alt"></i> 公开</span>' if note.publish %>
              <span class="opts pull-right">
                <a href="<%= edit_note_path(note.id) %>"><i class="fa fa-pencil"></i></a>
              </span>
            </div>
            <div class="info">
              <%= note.word_count %> <%= t("notes.chars") %>, <%= sanitize t("notes.created_at", time: timeago(note.created_at)) %>, <%= note.changes_count %> <%= t("notes.times_edit") %>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
    </div>

    <div class="panel-footer">
      <%= will_paginate @notes %>
    </div>
  </div>
</div>

<%= render "sidebar" %>
</div>

app/views/notes/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><%= t("notes.create_note")%></div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

app/views/notes/show.html.erb
<div id="notes" class="panel panel-default">
  <div class="panel-heading">
    <%= raw '<span><i class="fa fa-share-alt"></i> 公开</span> ' if @note.publish %>
     •
        共 <%= @note.word_count %> <%= t("notes.chars") %> • 由 <%= user_name_tag(@note.user) %> <%= sanitize t("notes.created_at", time: timeago(@note.created_at)) %> • <%= @note.hits %> <%= t("common.read_times")%> • <%= @note.changes_count %> <%= t("notes.times_edit") %>
        <% if owner? @note %>
        <span class="opts pull-right">
          <%= link_to icon_tag("fa fa-pencil"), edit_note_path(@note),  title: t("common.edit") %>
          <%= link_to icon_tag("fa fa-trash"), note_path(@note), 'data-confirm' => t("common.confirm_delete"), method: :delete, title: t("common.confirm_delete") %>
        </span>
        <% end %>
  </div>

  <div class="panel-body markdown">
    <%= markdown(@note.body) %>
  </div>

  <% if @note.publish %>
  <div class="panel-footer clearfix">
  <label><%= t("notes.page_link")%></label>
  <%= note_url(@note) %>
  </div>
  <% end %>
</div>