config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  resources :apps
  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: 'home#index'

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind' => 'users#auth_unbind', as: 'unbind_account'
  post 'account/update_private_token' => 'users#update_private_token', as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id' => 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed' => 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last' => 'topics#recent', as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
      post :ban
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search' => 'search#index', as: 'search'

  namespace :cpanel do
    root to: 'home#index'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
  end

  get 'api' => 'home#api', as: 'api'
  get 'twitter' => 'home#twitter', as: 'twitter'
  get 'markdown' => 'home#markdown', as: 'markdown'

  require 'dispatch'
  mount Api::Dispatch => '/api'

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get 'users/city/:id' => 'users#city', as: 'location_users'
  get 'users' => 'users#index', as: 'users'
  resources :users, path: '' do
    member do
      get :topics
      get :favorites
      get :notes
      get :blocked
      post :block
      post :unblock
      post :follow
      post :unfollow
      get :followers
      get :following
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/models/notification/topic.rb
module Notification
  class Topic < Base
    belongs_to :topic, class_name: 'Topic'

    delegate :body, to: :topic, prefix: true, allow_nil: true

    def notify_hash
      return {} if topic.blank?
      {
        title: '发表了新话题',
        content: topic_body[0, 30],
        content_path: content_path
      }
    end

    def actor
      topic.try(:user)
    end

    def content_path
      return '' if topic.blank?
      url_helpers.topic_path(topic.id)
    end
  end
end

app/controllers/cpanel/topics_controller.rb
module Cpanel
  class TopicsController < ApplicationController
    def index
      @topics = Topic.unscoped.desc(:_id).includes(:user).paginate page: params[:page], per_page: 30
    end

    def show
      @topic = Topic.unscoped.find(params[:id])
    end

    def new
      @topic = Topic.new
    end

    def edit
      @topic = Topic.unscoped.find(params[:id])
    end

    def create
      @topic = Topic.new(params[:topic].permit!)

      if @topic.save
        redirect_to(cpanel_topics_path, notice: 'Topic was successfully created.')
      else
        render action: 'new'
      end
    end

    def update
      @topic = Topic.unscoped.find(params[:id])

      if @topic.update_attributes(params[:topic].permit!)
        redirect_to(cpanel_topics_path, notice: 'Topic was successfully updated.')
      else
        render action: 'edit'
      end
    end

    def destroy
      @topic = Topic.unscoped.find(params[:id])
      @topic.destroy_by(current_user)

      redirect_to(cpanel_topics_path)
    end

    def undestroy
      @topic = Topic.unscoped.find(params[:id])
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(cpanel_topics_path)
    end

    def suggest
      @topic = Topic.unscoped.find(params[:id])
      @topic.update_attribute(:suggested_at, Time.now)
      CacheVersion.topic_last_suggested_at = Time.now
      redirect_to(cpanel_topics_path, notice: "Topic:#{params[:id]} suggested.")
    end

    def unsuggest
      @topic = Topic.unscoped.find(params[:id])
      @topic.update_attribute(:suggested_at, nil)
      CacheVersion.topic_last_suggested_at = Time.now
      redirect_to(cpanel_topics_path, notice: "Topic:#{params[:id]} unsuggested.")
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy,
                                     :favorite, :unfavorite, :follow, :unfollow, :suggest, :unsuggest, :ban]
  caches_action :feed, :node_feed, expires_in: 1.hours

  def index
    Rack::MiniProfiler.step('@suggest_topics') do
      @suggest_topics = Topic.without_hide_nodes.suggest.fields_for_list.limit(3).to_a
      @suggest_topic_ids = @suggest_topics.collect(&:id)
    end

    Rack::MiniProfiler.step('find_topics') do
      @topics = Topic.last_actived.where(:_id.nin => @suggest_topic_ids)
      if current_user
        @topics = @topics.without_nodes(current_user.blocked_node_ids)
        @topics = @topics.without_users(current_user.blocked_user_ids)
      else
        @topics = @topics.without_hide_nodes
      end
      @topics = @topics.fields_for_list
      @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)
    end

    set_seo_meta t('menu.topics'), "#{Setting.app_name}#{t('menu.topics')}"
  end

  def feed
    @topics = Topic.without_hide_nodes.recent.without_body.limit(20).includes(:node, :user, :last_reply_user)
    render layout: false
  end

  def node
    @node = Node.find(params[:id])
    @topics = @node.topics.last_actived.fields_for_list
    @topics = @topics.includes(:user).paginate(page: params[:page], per_page: 15)
    title = @node.jobs? ? @node.name : "#{@node.name} &raquo; #{t('menu.topics')}"
    set_seo_meta title, "#{Setting.app_name}#{t('menu.topics')}#{@node.name}", @node.summary
    render action: 'index'
  end

  def node_feed
    @node = Node.find(params[:id])
    @topics = @node.topics.recent.without_body.limit(20)
    render layout: false
  end

  %w(no_reply popular).each do |name|
    define_method(name) do
      @topics = Topic.without_hide_nodes.send(name.to_sym).last_actived.fields_for_list.includes(:user)
      @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)

      set_seo_meta [t("topics.topic_list.#{name}"), t('menu.topics')].join(' &raquo; ')
      render action: 'index'
    end
  end

  def recent
    @topics = Topic.without_hide_nodes.recent.fields_for_list.includes(:user)
    @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)
    set_seo_meta [t('topics.topic_list.recent'), t('menu.topics')].join(' &raquo; ')
    render action: 'index'
  end

  def excellent
    @topics = Topic.excellent.recent.fields_for_list.includes(:user)
    @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)

    set_seo_meta [t('topics.topic_list.excellent'), t('menu.topics')].join(' &raquo; ')
    render action: 'index'
  end

  def show
    @threads = []
    @topic = Topic.without_body.includes(:user).find(params[:id])

    @threads << Thread.new do
      @topic.hits.incr(1)
    end
    @threads << Thread.new do
      @node = @topic.node
    end

    @show_raw = params[:raw] == '1'

    @per_page = Reply.per_page
    # 默认最后一页
    params[:page] = @topic.last_page_with_per_page(@per_page) if params[:page].blank?
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1

    @threads << Thread.new do
      @replies = @topic.replies.unscoped.without_body.asc(:_id)
      @replies = @replies.paginate(page: @page, per_page: @per_page)

      check_current_user_liked_replies
    end
    @threads.each(&:join)

    check_current_user_status_for_topic
    set_special_node_active_menu

    set_seo_meta "#{@topic.title} &raquo; #{t('menu.topics')}"

    fresh_when(etag: [@topic, @has_followed, @has_favorited, @replies, @node, @show_raw])
  end

  def check_current_user_liked_replies
    return false unless current_user

    # 找出用户 like 过的 Reply，给 JS 处理 like 功能的状态
    @user_liked_reply_ids = []
    @replies.each do |r|
      unless r.liked_user_ids.index(current_user.id).nil?
        @user_liked_reply_ids << r.id
      end
    end
  end

  def check_current_user_status_for_topic
    return false unless current_user

    @threads << Thread.new do
      # 通知处理
      current_user.read_topic(@topic)
    end

    # 是否关注过
    @has_followed = @topic.follower_ids.index(current_user.id).nil?
    # 是否收藏
    @has_favorited = current_user.favorite_topic_ids.index(@topic.id).nil?
  end

  def set_special_node_active_menu
    case @node.try(:id)
    when Node.jobs_id
      @current = ['/jobs']
    end
  end

  def new
    @topic = Topic.new
    unless params[:node].blank?
      @topic.node_id = params[:node]
      @node = Node.find_by_id(params[:node])
      render_404 if @node.blank?
    end

    set_seo_meta "#{t('topics.post_topic')} &raquo; #{t('menu.topics')}"
  end

  def edit
    @topic = Topic.find(params[:id])
    @node = @topic.node

    set_seo_meta "#{t('topics.edit_topic')} &raquo; #{t('menu.topics')}"
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.node_id = params[:node] || topic_params[:node_id]

    if @topic.save
      redirect_to(topic_path(@topic.id), notice: t('topics.create_topic_success'))
    else
      render action: 'new'
    end
  end

  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if current_user.admin?
      @topic.admin_editing = true
    end

    if @topic.lock_node == false || current_user.admin?
      # 锁定接点的时候，只有管理员可以修改节点
      @topic.node_id = topic_params[:node_id]

      if current_user.admin? && @topic.node_id_changed?
        # 当管理员修改节点的时候，锁定节点
        @topic.lock_node = true
      end
    end
    @topic.title = topic_params[:title]
    @topic.body = topic_params[:body]

    if @topic.save
      redirect_to(topic_path(@topic.id), notice: t('topics.update_topic_success'))
    else
      render action: 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy_by(current_user)
    redirect_to(topics_path, notice: t('topics.delete_topic_success'))
  end

  def favorite
    current_user.favorite_topic(params[:id])
    render text: '1'
  end

  def unfavorite
    current_user.unfavorite_topic(params[:id])
    render text: '1'
  end

  def follow
    @topic = Topic.find(params[:id])
    @topic.push_follower(current_user.id)
    render text: '1'
  end

  def unfollow
    @topic = Topic.find(params[:id])
    @topic.pull_follower(current_user.id)
    render text: '1'
  end

  def suggest
    @topic = Topic.find(params[:id])
    @topic.update_attributes(excellent: 1)
    redirect_to @topic, success: '加精成功。'
  end

  def unsuggest
    @topic = Topic.find(params[:id])
    @topic.update_attribute(:excellent, 0)
    redirect_to @topic, success: '加精已经取消。'
  end

  def ban
    @topic = Topic.find(params[:id])
    @topic.update_attribute(:node_id, Node.no_point_id)
    redirect_to @topic, success: '已转移到 NoPoint 节点。'
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id)
  end
end

app/helpers/topics_helper.rb
require 'digest/md5'
module TopicsHelper
  def markdown(text)
    sanitize_markdown(MarkdownTopicConverter.format(text))
  end

  def topic_use_readed_text(state)
    case state
    when true
      t('topics.have_no_new_reply')
    else
      t('topics.has_new_replies')
    end
  end

  def topic_favorite_tag(topic)
    return '' if current_user.blank?
    class_name = ''
    link_title = '收藏'
    if current_user && current_user.favorite_topic_ids.include?(topic.id)
      class_name = 'followed'
      link_title = '取消收藏'
    end

    icon = raw(content_tag('i', '', class: 'fa fa-bookmark'))

    link_to(icon, '#', title: link_title, class: "bookmark #{class_name}", 'data-id' => topic.id)
  end

  def topic_follow_tag(topic)
    return '' if current_user.blank?
    return '' if topic.blank?
    return '' if owner?(topic)
    class_name = 'follow'
    followed = false
    if topic.follower_ids.include?(current_user.id)
      class_name = 'follow followed'
      followed = true
    end
    icon = content_tag('i', '', class: 'fa fa-eye')
    link_to(raw("#{icon} 关注"), '#', 'data-id' => topic.id, 'data-followed' => followed, class: class_name)
  end

  def topic_title_tag(topic)
    return t('topics.topic_was_deleted') if topic.blank?
    link_to(topic.title, topic_path(topic), title: topic.title)
  end

  def topic_excellent_tag(topic)
    return '' unless topic.excellent?
    content_tag(:i, '', title: '精华帖', class: 'fa fa-diamond')
  end

  def render_topic_last_reply_time(topic)
    l((topic.replied_at || topic.created_at), format: :short)
  end

  def render_topic_created_at(topic)
    timeago(topic.created_at, class: 'published')
  end

  def render_topic_last_be_replied_time(topic)
    timeago(topic.replied_at)
  end

  def render_topic_node_select_tag(topic)
    return if topic.blank?
    opts = {
      'data-width' => '140px',
      'data-live-search' => 'true',
      class: 'show-menu-arrow'
    }
    grouped_collection_select :topic, :node_id, Section.all, :sorted_nodes, :name, :id, :name,
                              { value: topic.node_id, prompt: '选择节点' }, opts
  end
end

app/views/topics/_ban_reason.html.erb
<% if @topic.node_id == Node.no_point_id %>
<div class="alert alert-warning alert-block">
  <h5 class="title">此贴已暂时被屏蔽!</h5>
  <div class="markdown">
    <%= markdown @topic.node.summary %>
  </div>
</div>
<% end %>

app/views/topics/_buttons.html.erb
<div class="opts">
  <%= likeable_tag(@topic) %>
  <%= topic_follow_tag(@topic) %>
  <%= topic_favorite_tag(@topic) %>
  <% if admin? %>
    <% if !@topic.suggested_at.blank? %>
    <%= link_to raw("<i class='fa fa-thumb-tack'></i> 取消"), unsuggest_cpanel_topic_path(@topic), 'data-confirm' => '确定要取消置顶么?', method: :post %>
    <% else %>
    <%= link_to raw("<i class='fa fa-thumb-tack'></i> 置顶"), suggest_cpanel_topic_path(@topic), 'data-confirm' => '确定要置顶么?', method: :post %>
    <% end %>
    <% if !@topic.excellent? %>
    <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), suggest_topic_path(@topic.id), title: "设为精华帖" , method: "patch", data: { confirm: "确定要设置成精华帖么？" } %>
    <% end %>
    <% if @topic.node_id != Node.no_point_id %>
    <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), ban_topic_path(@topic), method: 'post', title: "屏蔽此贴，移动到 NoPoint 节点" %>
    <% end %>
  <% end %>
  <span class="pull-right opts">
    <% if owner?(@topic) or admin? %>
    <%= link_to "", edit_topic_path(@topic), class: "fa fa-pencil", title: "修改本帖" %>
      <% if can?(:destroy, @topic) %>
      <%= link_to "", topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), class: "fa fa-trash", title: "删除本帖" %>
      <% end %>
    <% end %>
  </span>
</div>

app/views/topics/_editor_toolbar.html.erb
<div class="editor-toolbar">
  <div class="opts pull-right">
    <span class="dropdown dropdown-small" id="editor-toolbar-insert-code">
      <a href="#editor-toolbar-insert-code" data-toggle="dropdown" title="<%= t("topics.insert_codes") %>" href="#editor-toolbar-insert-code"><i class="fa fa-code"></i></a>
      <ul class="dropdown-menu insert-codes" role="menu">
        <%= insert_code_menu_items_tag %>
      </ul>
    </span>
    <%= link_to(icon_tag("fa fa-image"), "#", id: "topic-upload-image", rel: "twipsy", title: t("topics.add_image") )%>
    <input type="file" id="topic-upload-images" style="display:none" />
  </div>
  <ul class="nav nav-pills" style="clear:none;">
    <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
    <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
  </ul>
</div>

app/views/topics/_form.html.erb
<%= simple_form_for @topic, html: { class: "form" } do |f| %>
  <%= render "shared/error_messages", target: @topic %>
  <div class="form-group">
    <% if @topic.lock_node == false || admin? %>
    <div class="input-group">
      <span class="node-select input-group-btn">
        <%= render_topic_node_select_tag(@topic) %>
      </span>
      <%= f.text_field :title, class: "form-control", placeholder: "在这里填写标题" %>
    </div>
    <% else %>
      <%= f.text_field :title, class: "form-control", placeholder: "在这里填写标题" %>
    <% end %>
  </div>

  <%= render "editor_toolbar" %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control closewarning", rows: 20 %>
  </div>

  <div class="form-group">
    <%= f.submit t("common.save"), class: "btn btn-primary col-xs-2", 'data-disable-with' => t("common.saving") %>

    <div class="pull-right"><a href="/markdown" target="_blank"><i class="fa fa-tip"></i> 排版说明</a></div>
  </div>
<% end %>

app/views/topics/_node_info.html.erb
<% if !node.blank? %>
  <div class="node-info">
    <div class="name">
      <strong><%= node.name %></strong> <span class="total">共有 <%= render_node_topics_count(node) %> 个讨论主题</span>
      <div class="pull-right">
        <%= block_node_tag(node) %>
      </div>
    </div>
    <div class="summary">
      <%= sanitize_markdown node.summary_html %>
    </div>
  </div>

<% else %>
  <div class="filter pull-right">
    <span class="l">查看:</span>
    <a href="<%= topics_path %>"<%= " class=active" if action_name == "index" %>>默认</a> /
    <a href="<%= popular_topics_path %>" class="popular<%= " active" if action_name == "popular"  %>"><i class="fa fa-diamond"></i> 优质帖子</a> /
    <a href="<%= no_reply_topics_path %>" <%= " class=active" if action_name == "no_reply"  %>>无人问津</a> /
    <a href="<%= recent_topics_path %>" <%= " class=active" if action_name == "recent"  %>>最新创建</a>
  </div>
<% end %>

app/views/topics/_sidebar_box_node_recent_topics.html.erb
<% cache(["sidebar_for_node_recent_topics", topic.node_id, Time.now.strftime("%Y-%m-%d %H")]) do %>
  <%
  limit = [[topic.replies_count, 1].max, 10].min
  topics = Topic.where(:id.ne => topic.id, :node_id => topic.node_id).recent.limit(limit)
  %>

  <% if topics.present? %>
  <div class="panel panel-default">
    <div class="panel-heading"><%= t("topics.node_recent_topics") %></div>
    <ul class="list-group">
    <% topics.each do |item| %>
      <li class="list-group-item"><%= link_to(truncate(item.title, length: 30), topic_path(item), title: item.title) %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

app/views/topics/_sidebar_box_tips.html.erb
<div class="panel panel-default">
  <div class="panel-heading">小帖士</div>
  <div class="panel-body">
    <%= random_tips %>
  </div>
</div>

app/views/topics/_sidebar_for_topic_index.html.erb
<% if can? :create, Topic %>
  <% cache(["sidebar_new_topic_box",SiteConfig.new_topic_dropdown_node_ids]) do %>
    <div class="panel panel-default clearfix">
      <div class="panel-body">
        <div class="btn-group pull-left">
          <%= link_to(t("topics.start_a_new_topic_button"), new_topic_path, class: "btn btn-primary" )%>
          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% Node.new_topic_dropdowns.each do |node| %>
              <li>
                <%= link_to(node.name, new_topic_path(node: node.id)) %>
              </li>
            <% end %>
          </ul>
        </div>

        <%= link_to(sanitize("<span class='icon icons-rss'></span> RSS"), feed_topics_url, title: t("topics.subscribe_with_rss", name: Setting.app_name), class: "pull-right feed-button btn btn-default", target: "_blank") %>
      </div>
    </div>
  <% end %>
<% end %>

<% if current_user && current_user.newbie? %>
<div class="panel panel-default">
  <div class="panel-heading">新手必读</div>
  <div class="panel-body">
    <%= raw SiteConfig.newbie_notices %>
  </div>
</div>
<% end %>

<%= render "topics/sidebar_box_tips" %>

<%= raw SiteConfig.topic_index_sidebar_html %>

<% cache(["sidebar_statistics",Time.now.strftime("%Y-%m-%d %H")]) do %>
<div class="panel panel-default">
  <div class="panel-heading"><%= t("common.statics")%></div>
  <ul class="list-group">
    <li class="list-group-item">社区会员: <%= User.unscoped.count %> 人</li>
    <li class="list-group-item">帖子数: <%= Topic.unscoped.count %> 个</li>
    <li class="list-group-item">回帖数: <%= Reply.unscoped.count %> 条</li>
  </ul>
</div>
<% end %>

app/views/topics/_topic_info.html.erb
<div class="panel-heading media clearfix">
  <div class="media-body">
    <h1 class="media-heading"><%= topic.title %></h1>
    <div class="info">
      <%= render_node_name(topic.node_name,topic.node_id) %>
       ·
      <%= user_name_tag(topic.user, data: { author: true }) %>
       ·
      <%= raw t("common.created_at", time: timeago(topic.created_at))%>
      <% if !topic.last_reply_user_login.blank? %>
         ·
        <%= t("common.last_by")%> <%= user_name_tag(topic.last_reply_user_login) %> <%= raw t("common.reply_at", time: timeago(topic.replied_at))%>
      <% end %>
       ·
      <%= topic.hits %> <%= t("common.read_times")%>
    </div>
  </div>
  <div class="avatar media-right">
    <%= user_avatar_tag(@topic.user, :normal) %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">修改话题 <span class="pull-right hidden-xs"><%= topic_title_tag(@topic) %></span></div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

app/views/topics/show.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    Topics.replies_per_page = <%= @per_page %>;
    <% if current_user && !@user_liked_reply_ids.blank? %>
    Topics.user_liked_reply_ids = [<%= @user_liked_reply_ids.join(",") %>];
    <% end %>
    $(document).ready(function(){
      <% if admin? %>
        $("#replies .reply a.edit").css('display','inline-block');
      <% elsif current_user %>
        $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display','inline-block');
      <% end %>
    })
  </script>
<% end %>

<div class="row">
  <div class="col-md-9">
    <div class="topic-detail panel panel-default">
      <%= render partial: "topics/topic_info", locals: { topic: @topic } %>

      <div class="panel-body markdown">
        <%= raw SiteConfig.before_topic_html %>
        <%= raw @topic.body_html %>


        <%= raw SiteConfig.after_topic_html %>
        <%= social_share_button_tag h("#{@topic.title} via: @#{Setting.twitter_id} ") %>
      </div>

      <% if @topic.excellent? %>
        <div class="label-awesome">
          <i class="fa fa-diamond awesome"></i> 本帖已被设为精华帖！
          <% if admin? %>
          <div class="pull-right">
            <%= link_to icon_tag("close"), unsuggest_topic_path(@topic.id), data: { confirm: "确定要取消么？", method: "delete" } %>
          </div>
          <% end %>
        </div>
      <% end %>

      <div class="panel-footer clearfix">
        <%= render "buttons" %>
      </div>
    </div>

    <%= render partial: "ban_reason" %>

  <% if @replies.blank? %>
    <div class="no-result">
      <%= t("topics.no_replies") %>
    </div>
    <% else %>
    <div id="replies" class="panel panel-default" data-last-floor="<%= @replies.count %>">
      <div class="total panel-heading">
        共收到 <b><%= @topic.replies_count %></b> 条回复
      </div>
      <div class="items panel-body">
        <%= cache([@topic,params[:page],"raw:#{@show_raw}"]) do %>
          <%= render partial: "replies/reply", collection: @replies %>
        <% end %>
      </div>
      <div class="panel-footer clearfix">
        <%= will_paginate @replies, inner_window: 2, params: { anchor: 'replies' } %>
      </div>
    </div>
  <% end %>

  <% if current_user %>
    <div id="reply" class="panel panel-default">
      <div class="panel-heading">回帖</div>
      <div class="panel-body">
      <% if can? :create, Reply %>

        <%= render "editor_toolbar" %>
        <%= form_for(Reply.new, remote: true, url: topic_replies_path(@topic)) do |f| %>

          <div class="form-group">
            <%= f.text_area :body, class: "topic-editor form-control", rows: "4", tabindex: "1" %>
          </div>
          <div class="submit-buttons">
            <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2"><%= t("topics.submit_reply")%></button> <span class="help-inline" title="或者 Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

            <div class="pull-right"><a href="/markdown" target="_blank">排版说明</a></div>
          </div>
        <% end %>
      <% else %>
        <div class="alert alert-info">
          当前设置新手用户不能在 22:00 ~ 9:00 发帖。
        </div>
      <% end %>
      </div>
    </div>
  <% else %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: "topics/translation/need_login_to_reply" %>
      </div>
    </div>
  <% end %>
  </div>

<% if !mobile? %>
  <div class="sidebar col-md-3">
    <%= render "sidebar_box_tips" %>
    <%= render "sidebar_box_node_recent_topics", topic: @topic %>
  </div>
<% end %>
</div>