config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  resources :apps
  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: 'home#index'

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind' => 'users#auth_unbind', as: 'unbind_account'
  post 'account/update_private_token' => 'users#update_private_token', as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id' => 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed' => 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last' => 'topics#recent', as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
      post :ban
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search' => 'search#index', as: 'search'

  namespace :cpanel do
    root to: 'home#index'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
  end

  get 'api' => 'home#api', as: 'api'
  get 'twitter' => 'home#twitter', as: 'twitter'
  get 'markdown' => 'home#markdown', as: 'markdown'

  require 'dispatch'
  mount Api::Dispatch => '/api'

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get 'users/city/:id' => 'users#city', as: 'location_users'
  get 'users' => 'users#index', as: 'users'
  resources :users, path: '' do
    member do
      get :topics
      get :favorites
      get :notes
      get :blocked
      post :block
      post :unblock
      post :follow
      post :unfollow
      get :followers
      get :following
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/views/shared/_comment.html.erb
<div class="comment media">
  <div class="avatar media-left">
    <%= user_avatar_tag(comment.user, :normal) %>
  </div>
  <div class="media-body">
      <div class="info media-heading">
         <span class="name"><%= user_name_tag(comment.user) %></span> 发表于 <%= timeago(comment.created_at) %>
      </div>
      <div class="body markdown">
        <%= raw comment.body_html %>
      </div>
</div>
</div>

app/views/shared/_comments.html.erb
<%
comments = Comment.where(commentable_type: commentable.class.name, commentable_id: commentable.id).includes(:user)
new_comment = Comment.new(commentable_type: commentable.class.name, commentable_id: commentable.id)
%>
<div id="<%= commentable.class.name %>_<%= commentable.id %>_cell_comments" class="cell_comments panel panel-default">
  <div class="panel-heading">评论列表</div>
  <div class="panel-body">
    <% if !comments.blank? %>
    <%= render :partial => "/shared/comment", :collection => comments %>
    <% else %>
    <div class="no-result"><%= t("comments.no_comment") %>.</div>
    <% end %>
  </div>
</div>
<% if @current_user %>
<div id="<%= commentable.class.name %>_<%= commentable.id %>_cell_new_comment" class="cell_comments_new panel panel-default">
  <div class="panel-heading">发表新评论</div>
  <%= form_for(new_comment, remote: true, html: { class: "panel-body" }) do |f| %>
  <%= f.hidden_field :commentable_type %>
  <%= f.hidden_field :commentable_id %>
  <div class="form-group">
    <%= f.text_area :body, :class => "form-control", :rows => "3" %>
  </div>
  <div class="buttons">
    <%= f.submit t("comments.create_comment"), :class => "btn btn-primary", 'data-disable-with' => t("common.saving") %> <span class="help-inline">Ctrl+Enter</span>
  </div>
  <% end %>
</div>
<% end %>

app/views/shared/_editor_help_block.html.erb
<ul>
  <li>支持 Markdown 格式, <strong>**粗体**</strong>、~~删除线~~、<code>`单行代码`</code></li>
  <li>支持表情，见 <a href="http://www.emoji-cheat-sheet.com" target="_blank" rel="nofollow">Emoji cheat sheet</a></li>
  <li>按 “M” 键查看更多 <a href="#markdown_help_tip_modal" data-toggle="modal" data-keyboard="true" data-backdrop="true">帮助</a></li>
  <li>注意单词拼写，以及中英文排版，<a href="https://github.com/sparanoid/chinese-copywriting-guidelines" target="_blank">参考此页</a>
</ul>

<div class="modal fade" id="markdown_help_tip_modal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h4>格式说明</h4>
      </div>
      <div class="modal-body">
        <ul>
          <li>支持 Markdown 格式</li>
          <li><strong>**粗体**</strong>、~~删除线~~、<code>`单行代码`</code></li>
          <li>http://example.org 自动加链接</li>
          <li>@name  会链接到用户页面，并会通知他</li>
          <li>![Alt text here](http://foo.com/bar.jpg) 显示图片</li>
          <li>多行代码格式，使用 3 个`包起来，注意要换行，第一个 ``` 后面接语言名称(ruby,bash,html,css,python,erb,java... <a href="http://pygments.org/docs/lexers/" target="_blank">更多</a>)<br />
            比如这样：
              <pre style="border:0;background:#FFF;margin:0;">```ruby
    class Hello
    end
    ```</pre>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
 <div class="alert alert-block alert-danger">
   <a class="close" data-dismiss='alert' href="#">×</a>
   <p><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_hot_locations.html.erb
<% cache(["hot_locations",Time.now.strftime("%Y-%m-%d")]) do %>
<div class="panel panel-default">
  <div class="panel-heading"><%=t("common.hot_locations")%></div>
  <div class="panel-body location-list" style="text-align:center;">
      <% Location.hot.limit(12).each do |item| %>
        <span class="name"><%= location_name_tag(item) %></span>
      <% end %>
  </div>
</div>
<% end %>

app/views/shared/_index_sections.html.erb
<% cache(["index_locations",CacheVersion.section_node_updated_at]) do %>
<div id="sections" class="panel panel-default">
  <div class="panel-heading"><%= t("common.index_node_navigation")%></div>
  <div class="panel-body">
    <div class="row node-list">
      <% Section.includes(:nodes).all.each do |section| %>
      <div class="node media">
        <label class="media-left"><%= section.name %></label>
        <span class="nodes media-body">
          <% section.nodes.each do |node| %>
              <span class="name"><%= link_to(node.name, node_topics_path(node), title: node.name )%></span>
          <% end %>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>