config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications', authorized_applications: 'oauth/authorized_applications'
  end

  resources :apps
  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: 'home#index'

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind' => 'users#auth_unbind', as: 'unbind_account'
  post 'account/update_private_token' => 'users#update_private_token', as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id' => 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed' => 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last' => 'topics#recent', as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
      post :ban
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search' => 'search#index', as: 'search'

  namespace :cpanel do
    root to: 'home#index'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
  end

  get 'api' => 'home#api', as: 'api'
  get 'twitter' => 'home#twitter', as: 'twitter'
  get 'markdown' => 'home#markdown', as: 'markdown'

  require 'dispatch'
  mount Api::Dispatch => '/api'

  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get 'users/city/:id' => 'users#city', as: 'location_users'
  get 'users' => 'users#index', as: 'users'
  resources :users, path: '' do
    member do
      get :topics
      get :favorites
      get :notes
      get :blocked
      post :block
      post :unblock
      post :follow
      post :unfollow
      get :followers
      get :following
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/controllers/cpanel/home_controller.rb
module Cpanel
  class HomeController < ApplicationController
    def index
      @recent_topics = Topic.recent.limit(5)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @excellent_topics = Topic.excellent.recent.fields_for_list.limit(20).to_a

    fresh_when(etag: [@excellent_topics, SiteConfig.index_html])
  end

  def api
    @routes = []
    Api::Dispatch.routes.each do |route|
      next if route.route_method.blank?
      path = route.route_path
      path.sub!('(.:format)', '.json')
      path.sub!('/:version', '')

      r = {
        id: path.dasherize,
        method: route.route_method,
        name: path,
        params: route.route_params,
        desc: route.route_description
      }
      @routes << r
    end
    @routes.sort_by! { |a| a[:name] }
  end

  def twitter
    set_seo_meta t('menu.tweets')
  end

  def error_404
    render_404
  end

  def markdown
    set_seo_meta('Markdown Guide')
  end
end

app/views/home/api.html.erb
<% cache(["api", "v3.07"], expires_in: 1.days) do %>
<div class="panel panel-default api-doc">
  <div class="panel-heading">Ruby China API 目录</div>
  <div class="panel-body markdown">
    <h4>OAuth 2 / API 认证</h4>
    <p>
      在使用 API 之前，你需要 <%= link_to "注册应用", new_oauth_application_path, target: "_blank" %> 并获得可以 OAuth App 信息。并使用标准的 OAuth 2 实现登录，获得 <code>access_token</code> 信息。
    </p>
    <h5>OAuth 路径</h5>
    <ul>
      <li>https://<%= Setting.domain %>/oauth/authorize</li>
      <li>https://<%= Setting.domain %>/oauth/token</li>
      <li>https://<%= Setting.domain %>/oauth/revoke</li>
    </ul>
    <h4>Response 说明</h4>
    <p>所有 Response 采用 JSON 格式返回，请求状态通过 HTTP Status 返回</p>
    <h5>HTTP Status</h5>
    <ul>
      <li>200, 201 - 请求成功，或执行成功</li>
      <li>400 - 参数不符合 API 的要求、或者数据格式验证没有通过，请配合 Response Body 里面的 error 信息确定问题。</li>
      <li>401 - 用户认证失败，或缺少认证信息，比如 access_token 过期，或没传，可以尝试用 refresh_token 方式获得新的 access_token。</li>
      <li>403 - 当前用户对资源没有操作权限</li>
      <li>404 - 资源不存在。</li>
      <li>500 - 服务器异常</li>
    </ul>
    <p>错误的情况 Response Body 一定会是这样的格式: <code>{ "error" : "Error message" }</code></p>
    <h5>资源权限描述</h5>
    <p>在部分 API 的 response 内容里面你会看到 <code>abilities</code> 节点，这是特别标识当前 access_token 对应的用户对此资源的权限</p>
    <p>请参考源代码，确定那些路径是需要用户认证的，需要用户认证的路径，你需要带上 <code>access_token=?</code> 参数。</p>
    <strong>例如</strong>
    <%= markdown(%(```json
{ 
  "topic": {
    "id": 256170,
    ....,
    "abilities": { "update": true, "destroy": true }
  }
}
```))%>
    <ul>
      <li><code>update</code> - 是否有权限修改</li>
      <li><code>destroy</code> - 是否有权限删除</li>
    </ul>
    <h4>API 路由</h4>
    <p>下面是简单的 API 路由列表, 具体请参考源代码 <a href="https://github.com/ruby-china/ruby-china/blob/master/app/api" target="_blank">app/api</a></p>
    <p>URL 基本路径：<%= request.protocol %><%= Setting.domain %>/api/v3</p>
    <div class="row">
      <div class="col-md-3">
        <ul class="route-list">
          <% @routes.each do |route| %>
          <li><%= route[:method] %> <a href="#route-<%= route[:id] %>"><%= route[:name] %></a></li>
          <% end %>
        </ul>
      </div>
      <div class="routes col-md-9">
        <% @routes.each do |route| %>
        <div class="route" id="route-<%= route[:id] %>">
          <h5><label><%= route[:method] %></label> <%= route[:name] %></h5>
          <div class="content">
            <div class="desc markdown"><%= markdown(route[:desc] || "暂无") %></div>
            <% if route[:params].count > 0 %>
            <h6>Params</h6>
            <table class="table table-striped table-bordered params">
              <thead>
                <th>参数名</th>
                <th>类型</th>
                <th>必填</th>
                <th>默认值</th>
                <th>值范围</th>
                <th>说明</th>
              </thead>
              <tbody>
                <% route[:params].each do |k,param| %>
                <%
                if not param.is_a?(Hash)
                  param = { type: "String", required: true, desc: "主键" }
                end
                %>
                <tr>
                  <td class="field"><%= k %></td>
                  <td class="type"><%= param[:type] %></td>
                  <td class="required"><%= param[:required] %></td>
                  <td class="default"><%= param[:default] %></td>
                  <td class="values"><%= param[:values] %></td>
                  <td><%= markdown(param[:desc] || "") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <h4>Example</h4>
    <div style="margin-bottom:10px;">
      <p>我们用 Ruby 演示一下访问 /api/v3/hello.json 这个路径，其中包含 OAuth 2 的流程。</p>
      <p>这里用到 RubyGem <a href="https://github.com/intridea/oauth2" target="_blank">oauth2</a>
    </div>
    <%= markdown(%(
```ruby
=> require "oauth2"
=> client = OAuth2::Client.new('client id', 'secret', site: 'https://ruby-china.org')
=> access_token = client.password.get_token('username', 'password')
=> Faraday.get("https://ruby-china.org/api/v3/hello.json?access_token=\#{access_token.token}").body
{ 'current_user' : 'username' }
```
)) %>
  </div>
</div>
<% end %>

app/views/home/index.html.erb
<%= raw SiteConfig.index_html %>

<div class="row home-icons hidden-sm hidden-xs">
  <div class="col-md-3">
    <div class="item item1">
      <div class="icon">
        <a href="<%= topics_path %>"><i class="fa fa-comments-o"></i></a>
      </div>
      <div class="text">
        <a href="<%= topics_path %>">Ruby 社区 <i class="pull-right fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="item item2">
      <div class="icon">
        <a href="<%= pages_path %>"><i class="fa fa-support"></i></a>
      </div>
      <div class="text">
        <a href="<%= pages_path %>">技术文档 <i class="pull-right fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="item item3">
      <div class="icon">
        <a href="<%= jobs_path %>"><i class="fa fa-users"></i></a>
      </div>
      <div class="text">
        <a href="<%= jobs_path %>" title="Ruby 相关的招聘与求职">招聘与求职 <i class="pull-right fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="item item4">
      <div class="icon">
        <a href="<%= popular_topics_path %>"><i class="fa fa-diamond"></i></a>
      </div>
      <div class="text">
        <a href="<%= popular_topics_path %>">精华文章 <i class="pull-right fa fa-arrow-right"></i></a>
      </div>
    </div>
  </div>
</div>

<div class="home_suggest_topics panel panel-default">
  <div class="panel-heading">社区精华帖</div>
  <div class="panel-body topics row">
    <%
      odd_topics, even_topics = @excellent_topics.partition.each_with_index { |t, i| i.odd?  }
    %>
    <div class="col-md-6 topics-group">
      <% cache([odd_topics, "odd"]) do %>
        <%= render partial: "topics/topic", collection: odd_topics, locals: { suggest: false } %>
      <% end %>
    </div>

    <div class="col-md-6 topics-group">
      <% cache([even_topics, "even"]) do %>
        <%= render partial: "topics/topic", collection: even_topics, locals: { suggest: false } %>
      <% end %>
    </div>
  </div>
  <div class="panel-footer">
    <%= link_to "查看更多精华帖...", excellent_topics_path %>
  </div>
</div>

<% if !mobile? %>
  <%= render "/shared/index_sections" %>
  <%= render "/shared/hot_locations" %>
<% end %>

app/views/home/markdown.html.erb
<% cache(['markdown-guide', Digest::MD5.hexdigest(MARKDOWN_DOC)]) do %>
<div class="panel markdown panel-default">
  <div class="panel-body">
    <h1>Markdown 教程</h1>
    <div class="row">
      <div class="col-md-6">
        <pre><code><%= MARKDOWN_DOC %></code></pre>
      </div>
      <div class="col-md-6">
        <%= markdown(MARKDOWN_DOC)%>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/home/twitter.html.erb
<%= raw SiteConfig.twitter_page_html %>